// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIhWOBOregq9l7CPddUDiuao20zB-Hzso',
    appId: '1:790943371145:web:6d4370a08ab84cd8c55b58',
    messagingSenderId: '790943371145',
    projectId: 'flutter-web-connection-5b8e3',
    authDomain: 'flutter-web-connection-5b8e3.firebaseapp.com',
    storageBucket: 'flutter-web-connection-5b8e3.appspot.com',
    measurementId: 'G-M1KFSYQNGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJIONgzWyJ4HO8yonQ9jSdXXdg0Gb5mUQ',
    appId: '1:790943371145:android:3870ad5a84bf3684c55b58',
    messagingSenderId: '790943371145',
    projectId: 'flutter-web-connection-5b8e3',
    storageBucket: 'flutter-web-connection-5b8e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFrz0OK1QXSqBb61kevl6LulMfJvjatH0',
    appId: '1:790943371145:ios:954741237dfe778fc55b58',
    messagingSenderId: '790943371145',
    projectId: 'flutter-web-connection-5b8e3',
    storageBucket: 'flutter-web-connection-5b8e3.appspot.com',
    iosBundleId: 'com.example.websiteDesa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFrz0OK1QXSqBb61kevl6LulMfJvjatH0',
    appId: '1:790943371145:ios:954741237dfe778fc55b58',
    messagingSenderId: '790943371145',
    projectId: 'flutter-web-connection-5b8e3',
    storageBucket: 'flutter-web-connection-5b8e3.appspot.com',
    iosBundleId: 'com.example.websiteDesa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIhWOBOregq9l7CPddUDiuao20zB-Hzso',
    appId: '1:790943371145:web:3d66f58638e34b28c55b58',
    messagingSenderId: '790943371145',
    projectId: 'flutter-web-connection-5b8e3',
    authDomain: 'flutter-web-connection-5b8e3.firebaseapp.com',
    storageBucket: 'flutter-web-connection-5b8e3.appspot.com',
    measurementId: 'G-XK18D850EQ',
  );
}
